persist KYC attributes before calling AML program

diff --git a/src/kyclogic/taler-exchange-helper-converter-oauth2-test-full_name b/src/kyclogic/taler-exchange-helper-converter-oauth2-test-full_name
--- a/src/kyclogic/taler-exchange-helper-converter-oauth2-test-full_name
+++ b/src/kyclogic/taler-exchange-helper-converter-oauth2-test-full_name
@@ -28,16 +28,54 @@ set -eu
 
 echo "Running $0" 1>&2
 
-# FIXME: use getopt properly here, also support
-# -h, -v, -V, ...
+# Exit, with error message (hard failure)
+function exit_fail() {
+  echo " FAIL: " "$@" >&2
+  EXIT_STATUS=1
+  exit "$EXIT_STATUS"
+}
 
-if [ "${1:-no}" = "-o" ]
-then
-    # This converter produces a full name and birthdate.
-    echo "full_name"
-    echo "birthdate"
-    exit 0
-fi
+CONF="$HOME/.config/taler-exchange.conf"
+VERBOSE=0
+
+while getopts 'c:hovV' OPTION;
+do
+    case "$OPTION" in
+        c)
+            # shellcheck disable=SC2034
+            CONF="$OPTARG"
+            ;;
+        h)
+            echo "This is a KYC measure program that freezes the account and flags it for manual investigation. This is the ultimate fallback measure."
+            echo 'Supported options:'
+            echo '  -a           -- show required attributes'
+            # shellcheck disable=SC2016
+            echo '  -c $CONF     -- set configuration'
+            echo '  -h           -- print this help'
+            echo '  -i           -- show required inputs'
+            echo '  -r           -- show required context'
+            echo '  -v           -- show version'
+            echo '  -V           -- be verbose'
+            exit 0
+            ;;
+        o)
+            # This converter produces a full name and birthdate.
+            echo "full_name"
+            echo "birthdate"
+            exit 0
+            ;;
+        v)
+            echo "$0 v0.0.0"
+            exit 0
+            ;;
+        V)
+            VERBOSE=1
+            ;;
+        ?)
+        exit_fail "Unrecognized command line option"
+        ;;
+    esac
+done
 
 # First, check everything we expect is in stdin.
 J=$(jq -r 'def get($k):
