fix #9075: add -c option to AML programs, also enable -h/-v/-V and move to short options

diff --git a/src/kyclogic/taler-exchange-helper-measure-test-form b/src/kyclogic/taler-exchange-helper-measure-test-form
--- a/src/kyclogic/taler-exchange-helper-measure-test-form
+++ b/src/kyclogic/taler-exchange-helper-measure-test-form
@@ -18,31 +18,67 @@
 # Hard error reporting on.
 set -eu
 
-echo "Running $0" 1>&2
 
-# This is a KYC measure program that checks the output
-# of a simple FORM submission, and if it passed,
-# increases all limits to EUR:1000.
-# (and doesn't impose any other limits)
+# Exit, with error message (hard failure)
+function exit_fail() {
+    echo " FAIL: " "$@" >&2
+    EXIT_STATUS=1
+    exit "$EXIT_STATUS"
+}
 
-if [ "${1:-no}" = "--required-context" ]
+CONF="$HOME/.config/taler.conf"
+VERBOSE=0
+
+while getopts 'ac:hrvV' OPTION;
+do
+    case "$OPTION" in
+        a)
+            # This AML program expects as inputs a full_name
+            # and a birthdate.
+            echo "full_name"
+            echo "birthdate"
+            exit 0
+            ;;
+        c)
+            # shellcheck disable=SC2034
+            CONF="$OPTARG"
+            ;;
+        h)
+            echo "This is a KYC measure program that checks the output of a simple FORM submission, and if it passed, increases all limits to EUR:1000. (and does not impose any other limits)"
+            echo 'Supported options:'
+            echo '  -a           -- show required attributes'
+            # shellcheck disable=SC2016
+            echo '  -c $CONF     -- set configuration'
+            echo '  -h           -- print this help'
+            echo '  -r           -- show required context'
+            echo '  -v           -- show version'
+            echo '  -V           -- be verbose'
+            ;;
+        r)
+            # No context is required.
+            exit 0
+            ;;
+        v)
+            echo "$0 v0.0.0"
+            exit 0
+            ;;
+        V)
+            VERBOSE=1
+            ;;
+        ?)
+        exit_fail "Unrecognized command line option"
+        ;;
+    esac
+done
+
+if [ 1 = "$VERBOSE" ]
 then
-    # No context is required.
-    exit 0
-fi
-
-if [ "${1:-no}" = "--required-attributes" ]
-then
-    # This AML program expects as inputs a full_name
-    # and a birthdate.
-    echo "full_name"
-    echo "birthdate"
-    exit 0
+    echo "Running $0" 1>&2
 fi
 
 # First, check everything we expect is in stdin.
 A=$(jq -r .attributes)
-J=$(echo $A | jq -r 'def get($k):
+J=$(echo "$A" | jq -r 'def get($k):
              if has($k)
                then .[$k]
                else error("attribute missing")
